### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by oksie-roksie** [oksie-roksie/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Oksana-coder** [comment]
Phone: +38 063 8444186
Email: 8444186@gmail.com
Skype: oksana-palamarchuk
