### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by oksie-roksie** [oksie-roksie/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Oksana-coder** [comment]
**Work experience** 

**IT related:**
Fullstack Student @ GoIT Courses, Kyiv 
October 2020 - present

**Other:**		
_Marketing Intern_ @ Aggreko Deutschland, Berlin
April 2019 – September 2020 
- collaborated with various departments within the organisation to successfully launch the product and deliver necessary marketing materials

_Project Admin_ @ Weber-Stephen Products (EMEA), Berlin
February 2017 – March 2019 	
- assisted with project management and process optimisation with the result of achieving project goals  	

_English Trainer_ @ SGS Ukraine, Odesa			
2015 - 2016 
- improved employees English communication skills across the company office in Odesa

_Training Manager_ @ Starwood Hotels & Resorts, Odesa	
2014 – 2015 	
- worked closely  with all the departments to ensure that the employees training needs are met

_English Language Teacher_ @ Odessa National Maritime Academy, Odesa		
2008 – 2013 
- implemented the curriculum to successfully prepare students for the work with foreign ship crews
