### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by oksie-roksie** [oksie-roksie/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Oksana-coder** [comment]
**Education**
BA “International Business” @ HTW, Berlin
2016 - 2020 

MA “English Language and Literature” @ Odessa National University named after             I.I. Mechnikov, Odesa						
2003 – 2008 	

**Languages**
- Ukrainian, Russian: native
- English: C1
- German: B2

**Skills**
_Hard skills:_ HTML5, CSS3, JavaScript, AJAX, RESTful API, GIT, WebPack
_Soft skills:_ Teamwork, Flexibility, Patience, Attention to details, Time management

**Hobbies**
- Travelling
- Languages and cultures
- Lifelong learning
- Crossfit
